### ISSUE TITLE
API Keys committed

### ISSUE THREAD

**Issue by JoakimSoderberg** [FloThinksPi/PiCatFlap#3]
Hey, noticed you starred my catcierge project, so I checked your stuff out. You should try it with your catflap :)

Just a note, if I am not mistaken these keys should _NOT_ be committed and be public:
https://github.com/FloThinksPi/PiCatFlap/blob/master/node/PiCode/notify.py#L8

I suggest you put those in a local config file and read them from that instead... And regenerate those keys (or anyone on the interwebs can send you rude messages or worse).

**Comment by FloThinksPi** [comment]
@JoakimSoderberg whoops :D , ty for the hint :). 

I really was thinking about using tensorflow or other neural networks(maybe on own server on web for better learning) to determen if the cat has a gift for its owner :) , unfortunally i dont have much time atm.  But your idea of using high contrast and the outlines are gold :+1: . Only probmel is i intendet to use all that functionallity in a singe catflap sized device , maybe ill have to work with mirrors e.g. 
so when i have time ill finally make a video of that thing.

Thank you very much and kind regards from Germany!
